' @startmindmap 
' * 考核标准的常见误区
' ** 1.量化过度: \n过分依赖量化指标。
' ** 2.短视考核：\n短期业绩的过度强调。
' ** 3.通用化评价：\n缺乏差异化的考量。
' @endmindmap

@startmindmap 
* 组织变革步骤
** 1. 深入了解阻力的本质
** 2. 沟通和教育
** 3. 寻找盟友
** 4. 逐步实施变革
** 5. 评估和调整策略
@endmindmap