@startuml
hide footbox
box "WaitGroup"
actor Developer1
boundary "WaitGroup" as WG

Developer1 -> WG : Add(1)
Developer1 -> WG : Add(1)
WG -> Developer1 : Wait()
WG -> Developer1 : Done()
WG -> Developer1 : Done()
end box

box "Mutex"
actor Developer2
boundary "Mutex" as M
Developer2 -> M : Lock()
Developer2 -> M : Unlock()
Developer2 -> M : Lock()
Developer2 -> M : Unlock()
end box
@enduml
```