// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// 初始化依赖项
func InitializeServer(dsn string) *Server {
	database := NewDatabase(dsn)
	server := NewServer(database)
	return server
}
